export const COLORS_THEME = {
  blue: {
    key: "blue",
    bg: 'bg-blue-500',
    'hover:bg': 'hover:bg-blue-500',
    border: 'border-blue-500',
    outline: 'outline-blue-500',
    text: 'text-blue-500',
  },
  orange: {
    key: "orange",
    bg: 'bg-orange-500',
    'hover:bg': 'hover:bg-orange-500',
    border: 'border-orange-500',
    outline: 'outline-orange-500',
    text: 'text-orange-500',
  },
  red: {
    key: "red",
    bg: 'bg-red-500',
    'hover:bg': 'hover:bg-red-500',
    border: 'border-red-500',
    outline: 'outline-red-500',
    text: 'text-red-500',
  },
  green: {
    key: "green",
    bg: 'bg-green-500',
    'hover:bg': 'hover:bg-green-500',
    border: 'border-green-500',
    outline: 'outline-green-500',
    text: 'text-green-500',
  },
  emerald: {
    key: "emerald",
    bg: 'bg-emerald-500',
    'hover:bg': 'hover:bg-emerald-500',
    border: 'border-emerald-500',
    outline: 'outline-emerald-500',
    text: 'text-emerald-500',
  },
  yellow: {
    key: "yellow",
    bg: 'bg-yellow-500',
    'hover:bg': 'hover:bg-yellow-500',
    border: 'border-yellow-500',
    outline: 'outline-yellow-500',
    text: 'text-yellow-500',
  },
  amber: {
    key: "amber",
    bg: 'bg-amber-500',
    'hover:bg': 'hover:bg-amber-500',
    border: 'border-amber-500',
    outline: 'outline-amber-500',
    text: 'text-amber-500',
  },
  pink: {
    key: "pink",
    bg: 'bg-pink-500',
    'hover:bg': 'hover:bg-pink-500',
    border: 'border-pink-500',
    outline: 'outline-pink-500',
    text: 'text-pink-500',
  },
  rose: {
    key: "rose",
    bg: 'bg-rose-500',
    'hover:bg': 'hover:bg-rose-500',
    border: 'border-rose-500',
    outline: 'outline-rose-500',
    text: 'text-rose-500',
  },
  neutral: {
    key: "neutral",
    bg: 'bg-neutral-500',
    'hover:bg': 'hover:bg-neutral-500',
    border: 'border-neutral-500',
    outline: 'outline-neutral-500',
    text: 'text-neutral-500',
  },
  slate: {
    key: "slate",
    bg: 'bg-slate-500',
    'hover:bg': 'hover:bg-slate-500',
    border: 'border-slate-500',
    outline: 'outline-slate-500',
    text: 'text-slate-500',
  },
  purple: {
    key: "purple",
    bg: 'bg-purple-500',
    'hover:bg': 'hover:bg-purple-500',
    border: 'border-purple-500',
    outline: 'outline-purple-500',
    text: 'text-purple-500',
  },
  indigo: {
    key: "indigo",
    bg: 'bg-indigo-500',
    'hover:bg': 'hover:bg-indigo-500',
    border: 'border-indigo-500',
    outline: 'outline-indigo-500',
    text: 'text-indigo-500',
  },
  violet: {
    key: "violet",
    bg: 'bg-violet-500',
    'hover:bg': 'hover:bg-violet-500',
    border: 'border-violet-500',
    outline: 'outline-violet-500',
    text: 'text-violet-500',
  },
  sky: {
    key: "sky",
    bg: 'bg-sky-500',
    'hover:bg': 'hover:bg-sky-500',
    border: 'border-sky-500',
    outline: 'outline-sky-500',
    text: 'text-sky-500',
  },
  cyan: {
    key: "cyan",
    bg: 'bg-cyan-500',
    'hover:bg': 'hover:bg-cyan-500',
    border: 'border-cyan-500',
    outline: 'outline-cyan-500',
    text: 'text-cyan-500',
  },
} as const;

export type TColors = keyof typeof COLORS_THEME;

export function getColor(key: TColors) {
  return COLORS_THEME[key] ?? null;
}
